# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT!
all: Build/Network.exe
	@echo Run: Build/Network.exe
	@echo
	@./Build/Network.exe
Build/Network.exe: Build/ Build/list.o Build/main.o
	@echo Link: Network.exe
	@clang Build/*.o -o Build/Network.exe
Build/:
	@echo Create: Build/
	@mkdir Build/
Build/list.o: Source/list.c Source/list.h
	@echo Compile: list.c
	@clang -D_GNU_SOURCE -std=c17 -Weverything -Wno-unsafe-buffer-usage -ISource -c Source/list.c -o $@
Build/main.o: Source/main.c Source/list.h
	@echo Compile: main.c
	@clang -D_GNU_SOURCE -std=c17 -Weverything -Wno-unsafe-buffer-usage -ISource -c Source/main.c -o $@
clean:
	@echo Clean
	@rm -fr Build
